#Indicando o nome da aplicação
spring.application.name = contatos

#Indicando o caminho do DB
spring.datasource.url = jdbc:mysql://localhost:3306/telefones

#Indicar credenciais
spring.datasource.username = root
spring.datasource.password = Jv050905

#Permissao para atuação na camada DDL do DB
spring.jpa.hibernate.ddl-auto = update

#Tags opcionais par ao trabalho com JPA
#Habilitando exibição dos comandos SQL em console
spring.jpa.show-sql = true

#Formatando os comandos SQL para quebra de linhas
spring.jpa.properties.hibernate.format_sql = true