spring.application.name = cnpjapp

#Configura��es de conex�o com DB
# FIXME - Erro de url JDBC
spring.datasource.url = jdbc:h2:file:./data/bankdb
spring.datasource.username = teste
spring.datasource.password = 1234

#Propriedades do banco H2
spring.datasource.driverClassName = org.h2.Driver
spring.jpa.database-platform = org.hibernate.dialect.H2Dialect
spring.h2.console.enabled = true
spring.h2.console.path = /h2

#Solicitando acesso a camada DDL - Spring Data JPA
#Para ambientes Homol/Prod � interessante retirar essa op
spring.jpa.hibernate.ddl-auto = update
