package com.curso.GS2026.models;

public enum ReusableFor {
    NEW_SATELLITES,
    SPACE_STATIONS,
    SOLAR_PANELS,
    ANTENNAS,
    SPACECRAFT_COMPONENTS,
    COMMUNICATION_SYSTEMS,
    STRUCTURAL_COMPONENTS,
    BATTERIES,
    THERMAL_SYSTEMS,
    ELECTRONIC_CIRCUITS,
    PROPULSION_SYSTEMS,
    SCIENTIFIC_EQUIPMENT,
    INDUSTRIAL_RECYCLING,
    AEROSPACE_ENGINEERING,
    RESEARCH_AND_DEVELOPMENT,
    NOT_REUSABLE
}
