DROP TABLE USUARIO CASCADE CONSTRAINTS;
CREATE TABLE USUARIO(
    ID_USUARIO NUMBER PRIMARY KEY,
    NM_USUARIO VARCHAR2(100),
    EMAIL VARCHAR2(100),
    DT_NASC     DATE
    );
    
SELECT * FROM USUARIO;
INSERT INTO USUARIO VALUES (1, 'JOSE MARIA', 'jm1@gmail.com','02-12-98');
INSERT INTO USUARIO VALUES (2, 'JOSE MARIA', 'jm1@gmail.com','02-05-99');
SELECT SYSDATE FROM DUAL;

ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YY';
